/* API */
export const FETCH_ALL_FEEDBACKS = "FETCH_ALL_FEEDBACKS";
export const ON_FETCH_ALL_FEEDBACKS_SUCCESS = "ON_FETCH_ALL_FEEDBACKS_SUCCESS";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const ON_FETCH_ALL_USERS_SUCCESS = "ON_FETCH_ALL_USERS_SUCCESS";
export const FETCH_USERS_BY_FILTER = "FETCH_USERS_BY_FILTER";
export const ON_FETCH_USERS_BY_FILTER_SUCCESS =
  "ON_FETCH_USERS_BY_FILTER_SUCCESS";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const ON_FETCH_USER_DETAILS_SUCCESS = "ON_FETCH_USER_DETAILS_SUCCESS";
export const UPDATE_USERS_DATA = "UPDATE_USERS_DATA";
export const ON_UPDATE_USERS_DATA_SUCCESS = "ON_UPDATE_USERS_DATA_SUCCESS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const ON_UPDATE_USER_DETAILS_SUCCESS = "ON_UPDATE_USER_DETAILS_SUCCESS";
export const FETCH_ALL_MODELS = "FETCH_ALL_MODELS";
export const ON_FETCH_ALL_MODELS_SUCCESS = "ON_FETCH_ALL_MODELS_SUCCESS";
export const FETCH_MODELS_BY_FILTER = "FETCH_MODELS_BY_FILTER";
export const ON_FETCH_MODELS_BY_FILTER_SUCCESS =
  "ON_FETCH_MODELS_BY_FILTER_SUCCESS";
export const FETCH_MODEL_DETAILS = "FETCH_MODEL_DETAILS";
export const ON_FETCH_MODEL_DETAILS_SUCCESS = "ON_FETCH_MODEL_DETAILS_SUCCESS";
export const UPDATE_MODELS_DATA = "UPDATE_MODELS_DATA";
export const ON_UPDATE_MODELS_DATA_SUCCESS = "ON_UPDATE_MODELS_DATA_SUCCESS";
export const UPDATE_MODEL_DETAILS = "UPDATE_MODEL_DETAILS";
export const ON_UPDATE_MODEL_DETAILS_SUCCESS =
  "ON_UPDATE_MODEL_DETAILS_SUCCESS";
export const CREATE_MODEL = "CREATE_MODEL";
export const ON_CREATE_MODEL_SUCCESS = "ON_CREATE_MODEL_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const ON_REGISTER_USER_SUCCESS = "ON_REGISTER_USER_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const ON_LOGIN_USER_SUCCESS = "ON_LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const ON_LOGOUT_USER_SUCCESS = "ON_LOGOUT_USER_SUCCESS";
export const RELOAD_USER_DATA = "RELOAD_USER_DATA";
export const ON_RELOAD_USER_DATA_SUCCESS = "ON_RELOAD_USER_DATA_SUCCESS";
export const INIT_URL = "INIT_URL";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const WRITE_ERROR_MESSAGE = "WRITE_ERROR_MESSAGE";
export const DISPLAY_ERROR_MESSAGE = "DISPLAY_ERROR_MESSAGE";
export const DISPLAY_INFO_MESSAGE = "DISPLAY_INFO_MESSAGE";
export const DISPLAY_SUCCESS_MESSAGE = "DISPLAY_SUCCESS_MESSAGE";
export const DISPLAY_WARNING_MESSAGE = "DISPLAY_WARNING_MESSAGE";
export const DISPLAY_DEFAULT_MESSAGE = "DISPLAY_DEFAULT_MESSAGE";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ON_CLEAR_ERROR_MESSAGES = "ON_CLEAR_ERROR_MESSAGES";
export const HANDLE_ERROR = "HANDLE_ERROR";

// Customizer const
export const TOGGLE_COLLAPSED_NAV = "toggle_collapse_menu";
export const DRAWER_TYPE = "drawer_type";
export const FIXED_DRAWER = "fixed_drawer";
export const COLLAPSED_DRAWER = "collapsible";
export const MINI_DRAWER = "mini_drawer";
export const THEME_COLOR = "theme_color";
export const DARK_THEME = "dark_theme";
export const WINDOW_WIDTH = "window-width";
export const SWITCH_LANGUAGE = "switch-language";
export const CHANGE_DIRECTION = "change-direction";

export const CHANGE_NAVIGATION_STYLE = "change-navigation-style";
export const HORIZONTAL_NAVIGATION = "horizontal_navigation";
export const VERTICAL_NAVIGATION = "vertical_navigation";

export const HORIZONTAL_MENU_POSITION = "horizontal_menu_position";
export const ABOVE_THE_HEADER = "above_the_header";
export const INSIDE_THE_HEADER = "inside_the_header";
export const BELOW_THE_HEADER = "below_the_header";
